name: "e-distribución"
version: "1.0.1"
slug: "edistribucion"
description: "API local (sin depender de ningún servidor externo) para tus datos de consumo, potencia y suministros de e-distribución (Zona Privada)."
url: "https://github.com/agustinscaz/edistribucion-ha"
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
host_network: true
options:
  dni: ""
  password: ""
  base_url: "https://zonaprivada.edistribucion.com"
schema:
  dni: str
  password: password
  base_url: str
